version: "2"
run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  dupl:
    threshold: 200
  goconst:
    min-occurrences: 5
  funlen:
    lines: 120
    statements: 60

linters:
  enable:
    - errcheck
    - govet
    - dupl
    - goconst
    - misspell
    - funlen
    - ineffassign
    - staticcheck

issues:
  max-same-issues: 0
