-- Auto-generated from backend/migrations/init.sql.
-- Do not edit this file directly. Run: python scripts/sync_k8s_sql.py

CREATE DATABASE IF NOT EXISTS `caiyun`
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `caiyun`;

-- ============================================
-- 彩云项目数据库初始化脚本（终版）
-- 执行时间：2026-03-13
-- 特性：自动检测表和字段是否存在，存在则跳过
-- ============================================

DELIMITER $$

-- ============================================
-- 辅助函数：检查表是否存在
-- ============================================
DROP PROCEDURE IF EXISTS `CheckAndCreateTable`$$
CREATE PROCEDURE `CheckAndCreateTable`(
    IN p_table_name VARCHAR(100),
    IN p_create_sql TEXT
)
BEGIN
    SET @table_exists = (
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = DATABASE()
        AND table_name = p_table_name
    );

    IF @table_exists = 0 THEN
        SET @sql = p_create_sql;
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

-- ============================================
-- 辅助函数：添加列（如果不存在）
-- ============================================
DROP PROCEDURE IF EXISTS `AddColumnIfNotExists`$$
CREATE PROCEDURE `AddColumnIfNotExists`(
    IN p_table_name VARCHAR(100),
    IN p_column_name VARCHAR(100),
    IN p_column_def TEXT
)
BEGIN
    SET @col_exists = (
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
        AND table_name = p_table_name
        AND column_name = p_column_name
    );

    IF @col_exists = 0 THEN
        SET @sql = CONCAT('ALTER TABLE `', p_table_name, '` ADD COLUMN `', p_column_name, '` ', p_column_def);
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

-- ============================================
-- 辅助函数：修改 ENUM 字段（添加新值）
-- ============================================
DROP PROCEDURE IF EXISTS `ModifyEnumIfNotExists`$$
CREATE PROCEDURE `ModifyEnumIfNotExists`(
    IN p_table_name VARCHAR(100),
    IN p_column_name VARCHAR(100),
    IN p_enum_values TEXT
)
BEGIN
    SET @col_exists = (
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
        AND table_name = p_table_name
        AND column_name = p_column_name
    );

    IF @col_exists = 1 THEN
        SET @sql = CONCAT('ALTER TABLE `', p_table_name, '` MODIFY COLUMN `', p_column_name, '` ENUM(', p_enum_values, ') DEFAULT ''fixed''');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

-- ============================================
-- 辅助函数：创建索引（如果不存在）
-- ============================================
DROP PROCEDURE IF EXISTS `CreateIndexIfNotExists`$$
CREATE PROCEDURE `CreateIndexIfNotExists`(
    IN p_table_name VARCHAR(100),
    IN p_index_name VARCHAR(100),
    IN p_index_def TEXT
)
BEGIN
    SET @idx_exists = (
        SELECT COUNT(*)
        FROM information_schema.statistics
        WHERE table_schema = DATABASE()
        AND table_name = p_table_name
        AND index_name = p_index_name
    );

    IF @idx_exists = 0 THEN
        SET @sql = CONCAT('CREATE INDEX `', p_index_name, '` ON `', p_table_name, '` (', p_index_def, ')');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

DELIMITER ;

-- ============================================
-- 1. 创建用户表 (users)
-- ============================================
CALL CheckAndCreateTable('users', '
CREATE TABLE `users` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL COMMENT ''bcrypt哈希'',
    `email` VARCHAR(100),
    `role` VARCHAR(10) DEFAULT ''user'' COMMENT ''user, admin'',
    `token_version` INT NOT NULL DEFAULT 0 COMMENT ''JWT会话版本，用于吊销旧会话'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    INDEX `idx_username` (`username`),
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 1.1 创建登录失败锁定表 (login_fail_locks)
--     Redis 不可用时用于登录失败计数降级。
-- ============================================
CALL CheckAndCreateTable('login_fail_locks', '
CREATE TABLE `login_fail_locks` (
    `key_hash` CHAR(64) PRIMARY KEY COMMENT ''归一化登录名的 SHA-256 哈希'',
    `fail_count` INT NOT NULL DEFAULT 0 COMMENT ''连续失败次数'',
    `locked_until` TIMESTAMP NULL COMMENT ''锁定截止时间'',
    `expires_at` TIMESTAMP NOT NULL COMMENT ''计数窗口过期时间'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_login_fail_locks_expires_at` (`expires_at`),
    INDEX `idx_login_fail_locks_locked_until` (`locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 2. 创建账号表 (accounts)
-- ============================================
CALL CheckAndCreateTable('accounts', '
CREATE TABLE `accounts` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `phone` VARCHAR(20) NOT NULL,
    `auth` TEXT NOT NULL COMMENT ''Basic Auth字符串'',
    `token` TEXT COMMENT ''Token'',
    `jwt_token` TEXT COMMENT ''JWT Token'',
    `platform` VARCHAR(20) DEFAULT ''pc'',
    `expire_at` BIGINT COMMENT ''过期时间戳(毫秒)'',
    `cloud_count` INT DEFAULT 0 COMMENT ''当前云朵数量'',
    `remark` VARCHAR(200) COMMENT ''备注'',
    `is_active` BOOLEAN DEFAULT TRUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_phone` (`phone`),
    INDEX `idx_expire_at` (`expire_at`),
    INDEX `idx_deleted_at` (`deleted_at`),
    INDEX `idx_user_active` (`user_id`, `is_active`),
    UNIQUE KEY `uk_user_phone` (`user_id`, `phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 3. 创建任务日志表 (task_logs)
-- ============================================
CALL CheckAndCreateTable('task_logs', '
CREATE TABLE `task_logs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `account_id` BIGINT UNSIGNED NOT NULL,
    `task_type` VARCHAR(50) NOT NULL COMMENT ''signin, wechat, shake等'',
    `status` VARCHAR(20) DEFAULT ''pending'' COMMENT ''success, failed, pending'',
    `message` TEXT COMMENT ''执行结果/错误信息'',
    `cloud_gained` INT DEFAULT 0 COMMENT ''获得云朵数'',
    `execution_time` INT DEFAULT 0 COMMENT ''执行时长(毫秒)'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_account_id` (`account_id`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_deleted_at` (`deleted_at`),
    INDEX `idx_task_status` (`task_type`, `status`),
    INDEX `idx_account_created` (`account_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 4. 创建云朵统计表 (cloud_stats)
-- ============================================
CALL CheckAndCreateTable('cloud_stats', '
CREATE TABLE `cloud_stats` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `account_id` BIGINT UNSIGNED NOT NULL,
    `date` DATE NOT NULL COMMENT ''统计日期'',
    `cloud_count` INT NOT NULL COMMENT ''当日云朵数'',
    `cloud_diff` INT DEFAULT 0 COMMENT ''对比昨日变化'',
    `cloud_diff_week` INT DEFAULT 0 COMMENT ''对比上周变化'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `uk_user_account_date` (`user_id`, `account_id`, `date`),
    INDEX `idx_date` (`date`),
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 5. 创建系统配置表 (system_configs)
-- ============================================
CALL CheckAndCreateTable('system_configs', '
CREATE TABLE `system_configs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `key_name` VARCHAR(100) NOT NULL UNIQUE,
    `key_value` TEXT NOT NULL,
    `description` VARCHAR(200),
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_key_name` (`key_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 6. 创建任务配置表 (task_configs)
-- ============================================
CALL CheckAndCreateTable('task_configs', '
CREATE TABLE `task_configs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `task_type` VARCHAR(50) NOT NULL UNIQUE COMMENT ''任务类型标识'',
    `task_name` VARCHAR(50) NOT NULL COMMENT ''任务名称'',
    `description` VARCHAR(255) COMMENT ''任务描述'',
    `is_enabled` BOOLEAN DEFAULT TRUE COMMENT ''是否启用'',
    `sort_order` INT DEFAULT 0 COMMENT ''排序'',
    `run_in_batch` BOOLEAN DEFAULT TRUE COMMENT ''是否参与批量执行'',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 7. 创建商品表 (products)
-- ============================================
CALL CheckAndCreateTable('products', '
CREATE TABLE `products` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `prize_id` VARCHAR(100) NOT NULL UNIQUE COMMENT ''商品 ID(来自 API)'',
    `prize_name` VARCHAR(255) NOT NULL COMMENT ''商品名称'',
    `p_order` INT DEFAULT 0 COMMENT ''云朵价格'',
    `category` VARCHAR(100) DEFAULT ''未知分类'' COMMENT ''商品分类'',
    `daily_remainder_count` INT DEFAULT 0 COMMENT ''每日剩余数量'',
    `daily_limit_count` INT DEFAULT 0 COMMENT ''每日限购数量'',
    `daily_count` INT DEFAULT 0 COMMENT ''每日发放上限'',
    `image_url` VARCHAR(500) DEFAULT '''' COMMENT ''商品图片URL'',
    `stock_status` VARCHAR(20) DEFAULT ''unknown'' COMMENT ''库存状态'',
    `last_stock_check` DATETIME NULL COMMENT ''最后库存检查时间'',
    `memo` TEXT COMMENT ''商品备注信息'',
    `is_active` BOOLEAN DEFAULT TRUE COMMENT ''是否启用'',
    `is_deleted` BOOLEAN DEFAULT FALSE COMMENT ''是否已删除（软删除标记）'',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    INDEX `idx_prize_id` (`prize_id`),
    INDEX `idx_category` (`category`),
    INDEX `idx_active` (`is_active`),
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 8. 创建用户兑换账号表 (exchange_accounts)
-- ============================================
CALL CheckAndCreateTable('exchange_accounts', '
CREATE TABLE `exchange_accounts` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT ''用户 ID'',
    `account_id` BIGINT UNSIGNED NOT NULL COMMENT ''云盘账号 ID'',
    `phone` VARCHAR(20) NOT NULL COMMENT ''手机号'',
    `auth` TEXT NOT NULL COMMENT ''Basic Auth 字符串'',
    `token` TEXT COMMENT ''Token'',
    `jwt_token` TEXT COMMENT ''JWT Token'',
    `remark` VARCHAR(200) COMMENT ''备注'',
    `exchange_time_1` TIME DEFAULT ''10:00:00'' COMMENT ''第一次抢兑时间'',
    `exchange_time_2` TIME DEFAULT ''16:00:00'' COMMENT ''第二次抢兑时间'',
    `is_active` BOOLEAN DEFAULT TRUE COMMENT ''是否启用'',
    `max_concurrency` INT DEFAULT 1 COMMENT ''该账号最大并发数'',
    `retry_interval` INT DEFAULT 5 COMMENT ''失败重试间隔（秒）'',
    `last_exchange_at` TIMESTAMP NULL COMMENT ''最后抢兑时间'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_account_id` (`account_id`),
    INDEX `idx_active` (`is_active`),
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 9. 创建抢兑任务表 (exchange_tasks)
-- ============================================
CALL CheckAndCreateTable('exchange_tasks', '
CREATE TABLE `exchange_tasks` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT ''用户 ID'',
    `exchange_account_id` BIGINT UNSIGNED NOT NULL COMMENT ''兑换账号 ID'',
    `product_id` BIGINT UNSIGNED NOT NULL COMMENT ''商品 ID'',
    `prize_id` VARCHAR(100) NOT NULL COMMENT ''商品 ID(来自 API)'',
    `prize_name` VARCHAR(255) NOT NULL COMMENT ''商品名称'',
    `task_type` ENUM(''fixed'', ''long_term'', ''immediate'') DEFAULT ''fixed'' COMMENT ''任务类型: fixed-定时, long_term-长期, immediate-立即'',
    `max_attempts` INT DEFAULT 1 COMMENT ''最大抢兑次数'',
    `attempted_count` INT DEFAULT 0 COMMENT ''已抢兑次数'',
    `status` ENUM(''pending'', ''running'', ''completed'', ''cancelled'', ''failed'') DEFAULT ''pending'' COMMENT ''任务状态'',
    `priority` INT DEFAULT 0 COMMENT ''优先级：0-普通，1-重要，2-紧急'',
    `task_group` VARCHAR(50) DEFAULT '''' COMMENT ''任务分组标识'',
    `timeout_seconds` INT DEFAULT 30 COMMENT ''超时时间（秒）'',
    `max_retries` INT DEFAULT 3 COMMENT ''最大重试次数'',
    `retry_count` INT DEFAULT 0 COMMENT ''已重试次数'',
    `last_retry_at` DATETIME NULL COMMENT ''最后重试时间'',
    `last_attempt_at` TIMESTAMP NULL COMMENT ''最后抢兑时间'',
    `last_result` TEXT COMMENT ''最后抢兑结果'',
    `success_count` INT DEFAULT 0 COMMENT ''成功次数'',
    `fail_count` INT DEFAULT 0 COMMENT ''失败次数'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`exchange_account_id`) REFERENCES `exchange_accounts`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_account_id` (`exchange_account_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_task_type` (`task_type`),
    INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 10. 创建抢兑记录表 (exchange_records)
-- ============================================
CALL CheckAndCreateTable('exchange_records', '
CREATE TABLE `exchange_records` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT ''用户 ID'',
    `exchange_account_id` BIGINT UNSIGNED NOT NULL COMMENT ''兑换账号 ID'',
    `exchange_task_id` BIGINT UNSIGNED COMMENT ''抢兑任务 ID'',
    `product_id` BIGINT UNSIGNED NOT NULL COMMENT ''商品 ID'',
    `prize_id` VARCHAR(100) NOT NULL COMMENT ''商品 ID(来自 API)'',
    `prize_name` VARCHAR(255) NOT NULL COMMENT ''商品名称'',
    `status` ENUM(''success'', ''failed'') NOT NULL COMMENT ''抢兑结果'',
    `message` TEXT COMMENT ''抢兑结果消息'',
    `execution_time_ms` INT DEFAULT 0 COMMENT ''执行时长 (毫秒)'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_account_id` (`exchange_account_id`),
    INDEX `idx_task_id` (`exchange_task_id`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
');

-- ============================================
-- 11. 创建兑换任务执行历史表 (exchange_task_history)
-- ============================================
CALL CheckAndCreateTable('exchange_task_history', '
CREATE TABLE `exchange_task_history` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT UNSIGNED NOT NULL COMMENT ''任务 ID'',
    `account_id` BIGINT UNSIGNED NOT NULL COMMENT ''账号 ID'',
    `prize_id` VARCHAR(100) NOT NULL COMMENT ''商品 ID'',
    `action` VARCHAR(50) NOT NULL COMMENT ''操作类型：exchange, retry, timeout, cancel'',
    `result` VARCHAR(20) NOT NULL COMMENT ''结果：success, failed, timeout'',
    `message` TEXT COMMENT ''详细信息'',
    `duration_ms` INT DEFAULT 0 COMMENT ''执行时长（毫秒）'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_task_id` (`task_id`),
    INDEX `idx_account_id` (`account_id`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=''兑换任务执行历史表''
');

-- ============================================
-- 12. 创建公告表 (announcements)
-- ============================================
CALL CheckAndCreateTable('announcements', '
CREATE TABLE `announcements` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(200) NOT NULL COMMENT ''公告标题'',
    `content` TEXT NOT NULL COMMENT ''公告内容'',
    `is_popup` BOOLEAN DEFAULT FALSE COMMENT ''是否弹窗显示'',
    `is_top` BOOLEAN DEFAULT FALSE COMMENT ''是否置顶'',
    `is_published` BOOLEAN DEFAULT TRUE COMMENT ''是否发布'',
    `popup_count` INT DEFAULT 0 COMMENT ''弹窗显示次数'',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_is_published` (`is_published`),
    INDEX `idx_is_popup` (`is_popup`),
    INDEX `idx_is_top` (`is_top`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''公告表''
');

-- ============================================
-- 添加可能缺失的字段（兼容旧版本）
-- ============================================

-- users 表字段补充
CALL AddColumnIfNotExists('users', 'token_version', 'INT NOT NULL DEFAULT 0 COMMENT ''JWT会话版本，用于吊销旧会话'' AFTER `role`');

-- products 表字段补充
CALL AddColumnIfNotExists('products', 'daily_limit_count', 'INT DEFAULT 0 COMMENT ''每日限购数量'' AFTER `daily_remainder_count`');
CALL AddColumnIfNotExists('products', 'daily_count', 'INT DEFAULT 0 COMMENT ''每日发放上限'' AFTER `daily_limit_count`');
CALL AddColumnIfNotExists('products', 'image_url', 'VARCHAR(500) DEFAULT '''' COMMENT ''商品图片URL'' AFTER `daily_count`');
CALL AddColumnIfNotExists('products', 'stock_status', 'VARCHAR(20) DEFAULT ''unknown'' COMMENT ''库存状态'' AFTER `image_url`');
CALL AddColumnIfNotExists('products', 'last_stock_check', 'DATETIME NULL COMMENT ''最后库存检查时间'' AFTER `stock_status`');
CALL AddColumnIfNotExists('products', 'is_deleted', 'BOOLEAN DEFAULT FALSE COMMENT ''是否已删除（软删除标记）'' AFTER `is_active`');

-- exchange_accounts 表字段补充
CALL AddColumnIfNotExists('exchange_accounts', 'exchange_time_1', 'TIME DEFAULT ''10:00:00'' COMMENT ''第一次抢兑时间'' AFTER `remark`');
CALL AddColumnIfNotExists('exchange_accounts', 'exchange_time_2', 'TIME DEFAULT ''16:00:00'' COMMENT ''第二次抢兑时间'' AFTER `exchange_time_1`');
CALL AddColumnIfNotExists('exchange_accounts', 'max_concurrency', 'INT DEFAULT 1 COMMENT ''该账号最大并发数'' AFTER `is_active`');
CALL AddColumnIfNotExists('exchange_accounts', 'retry_interval', 'INT DEFAULT 5 COMMENT ''失败重试间隔（秒）'' AFTER `max_concurrency`');

-- accounts 表字段补充
CALL AddColumnIfNotExists('accounts', 'jwt_error_count', 'INT DEFAULT 0 COMMENT ''JWT获取失败次数'' AFTER `is_active`');

-- task_configs 表字段补充
CALL AddColumnIfNotExists('task_configs', 'description', 'VARCHAR(255) NULL COMMENT ''任务描述'' AFTER `task_name`');
CALL AddColumnIfNotExists('task_configs', 'run_in_batch', 'BOOLEAN DEFAULT TRUE COMMENT ''是否参与批量执行'' AFTER `sort_order`');

-- exchange_tasks 表字段补充
CALL AddColumnIfNotExists('exchange_tasks', 'priority', 'INT DEFAULT 0 COMMENT ''优先级：0-普通，1-重要，2-紧急'' AFTER `status`');
CALL AddColumnIfNotExists('exchange_tasks', 'task_group', 'VARCHAR(50) DEFAULT '''' COMMENT ''任务分组标识'' AFTER `priority`');
CALL AddColumnIfNotExists('exchange_tasks', 'timeout_seconds', 'INT DEFAULT 30 COMMENT ''超时时间（秒）'' AFTER `task_group`');
CALL AddColumnIfNotExists('exchange_tasks', 'max_retries', 'INT DEFAULT 3 COMMENT ''最大重试次数'' AFTER `timeout_seconds`');
CALL AddColumnIfNotExists('exchange_tasks', 'retry_count', 'INT DEFAULT 0 COMMENT ''已重试次数'' AFTER `max_retries`');
CALL AddColumnIfNotExists('exchange_tasks', 'last_retry_at', 'DATETIME NULL COMMENT ''最后重试时间'' AFTER `retry_count`');

-- 修改 task_type ENUM 字段，添加 immediate 类型
CALL ModifyEnumIfNotExists('exchange_tasks', 'task_type', '''fixed'', ''long_term'', ''immediate''');

-- ============================================
-- 添加可能缺失的索引
-- ============================================
-- 同一用户不能重复绑定同一手机号（数据库层兜底，避免并发请求绕过应用层查重）。
-- 使用生成列固定 NULL → 0 的方式实现"仅未软删记录参与唯一性"。
CALL CreateIndexIfNotExists('exchange_tasks', 'idx_exchange_tasks_priority_status', '`priority`, `status`');
CALL CreateIndexIfNotExists('exchange_tasks', 'idx_exchange_tasks_task_group', '`task_group`');
CALL CreateIndexIfNotExists('exchange_tasks', 'idx_exchange_tasks_timeout', '`timeout_seconds`, `status`');

-- ============================================
-- 插入默认系统配置数据
-- ============================================
INSERT IGNORE INTO `system_configs` (`key_name`, `key_value`, `description`) VALUES
('task_concurrency', '10', '任务并发数量'),
('task_schedule', '0 8 * * *', '定时任务执行时间(Cron表达式)'),
('token_cache_ttl', '86400', 'Token缓存时间(秒)'),
('exchange_concurrency', '10', '抢兑任务并发数量'),
('exchange_schedule_time_1', '10:00', '第一次抢兑时间'),
('exchange_schedule_time_2', '16:00', '第二次抢兑时间'),
('exchange_auto_update_products', 'true', '是否自动更新商品库'),
('exchange_update_time', '08:00', '商品库自动更新时间'),
('exchange_enable_priority', 'true', '是否启用任务优先级'),
('exchange_default_timeout', '30', '默认抢兑超时时间（秒）'),
('exchange_max_global_concurrency', '50', '全局最大并发数限制'),
('exchange_auto_retry_failed', 'true', '自动重试失败任务'),
('exchange_log_retention_days', '30', '日志保留天数'),
('exchange_immediate_enabled', 'false', '是否启用立即兑换功能'),
('product_categories', '其他权益奖品,视频类会员,音乐类会员,外卖美食权益,快递寄件券,云盘转存券,实用工具类,奶茶饮品权益,咖啡饮品权益,游戏礼包权益,全国通用流量权益', '商品分类列表');

-- ============================================
-- 插入默认任务配置数据
-- ============================================
INSERT IGNORE INTO `task_configs` (`task_type`, `task_name`, `is_enabled`, `sort_order`) VALUES
('signin', '每日签到', TRUE, 10),
('task_expansion_reward', '备份翻倍奖励', TRUE, 20),
('wechat', '微信签到', TRUE, 30),
('wxdraw', '微信抽奖', TRUE, 40),
('tasklist', '任务中心巡检', TRUE, 50),
('invitefriends', '邀请好友看电影', TRUE, 60),
('shake', '摇一摇', TRUE, 70),
('receive', '领取云朵', TRUE, 80),
('messagepush', '消息推送奖励', TRUE, 90),
('revivalreward', '复活卡奖励', TRUE, 95),
('backupgift', '备份礼包', TRUE, 100),
('garden', '果园', FALSE, 110),
('redpacket', 'AI红包', FALSE, 120),
('aicloud', 'AI云朵', FALSE, 130),
('cloudbattle', '云朵大作战', TRUE, 140),
('blindbox', '盲盒', FALSE, 150),
('cloudphone', '云手机红包', TRUE, 160),
('todaycloud', '今日云朵统计', TRUE, 165),
('after_task', '收尾清理', TRUE, 170);

-- ============================================
-- 清理辅助存储过程
-- ============================================
DROP PROCEDURE IF EXISTS `CheckAndCreateTable`;
DROP PROCEDURE IF EXISTS `AddColumnIfNotExists`;
DROP PROCEDURE IF EXISTS `ModifyEnumIfNotExists`;
DROP PROCEDURE IF EXISTS `CreateIndexIfNotExists`;

-- ============================================
-- 13. 创建WebSocket消息表 (web_socket_messages)
-- ============================================
CREATE TABLE IF NOT EXISTS `web_socket_messages` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `type` VARCHAR(50) NOT NULL COMMENT '消息类型',
    `data` TEXT COMMENT '消息数据(JSON格式)',
    `is_read` BOOLEAN DEFAULT FALSE COMMENT '是否已读',
    `is_delivered` BOOLEAN DEFAULT FALSE COMMENT '是否已送达',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `read_at` TIMESTAMP NULL DEFAULT NULL,
    `delivered_at` TIMESTAMP NULL DEFAULT NULL,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_is_delivered` (`is_delivered`),
    INDEX `idx_is_read` (`is_read`),
    INDEX `idx_created_at` (`created_at`),
    CONSTRAINT `fk_ws_messages_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='WebSocket消息表';

-- ============================================
-- 14. 创建审计日志表 (audit_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS `audit_logs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `username` VARCHAR(100) COMMENT '用户名',
    `action` VARCHAR(50) NOT NULL COMMENT '操作类型',
    `resource` VARCHAR(100) NOT NULL COMMENT '资源类型',
    `resource_id` VARCHAR(50) COMMENT '资源ID',
    `method` VARCHAR(10) COMMENT 'HTTP方法',
    `path` VARCHAR(500) COMMENT '请求路径',
    `ip` VARCHAR(50) COMMENT '客户端IP',
    `user_agent` VARCHAR(500) COMMENT '用户代理',
    `request_data` TEXT COMMENT '请求数据(JSON)',
    `response_data` TEXT COMMENT '响应数据(JSON)',
    `status_code` INT DEFAULT 0 COMMENT 'HTTP状态码',
    `error_msg` TEXT COMMENT '错误信息',
    `exec_time_ms` INT DEFAULT 0 COMMENT '执行时长(毫秒)',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_action` (`action`),
    INDEX `idx_resource` (`resource`),
    INDEX `idx_created_at` (`created_at`),
    CONSTRAINT `fk_audit_logs_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审计日志表';

-- ============================================
-- 初始化完成
-- ============================================
